version: '3'

networks:
    datapipeline:
        driver: bridge

services:
  master:
    image: docker.io/bitnami/spark:3.3
#    mem_limit: 512m
#    cpus: '0.25'
    container_name: spark-master
    volumes:
      - ./spark:/spark
      - ./spark/Scala/my_jars:/opt/bitnami/spark/my_jars
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      - datapipeline

  spark-worker:
    image: docker.io/bitnami/spark:3.3
#    mem_limit: 1g
#    cpus: '0.25'
    container_name: spark-worker
    volumes:
      - ./spark:/spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - datapipeline

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    mem_limit: 256m
    cpus: '0.25'
    container_name: kafka-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - datapipeline

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    mem_limit: 512m
    cpus: '0.25'
    container_name: kafka-broker
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - datapipeline